 ## NumPy Practice Questions

### Part 1: Basic Array Operations

In [13]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.argmax())
print(arr.argmin())
print(arr.mean())
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))

105
30
5
5
0
17.5
17.5
72.91666666666667
8.539125638299666


### Part 2: Array Creation Functions

In [14]:
#1. Create a 4×4 array filled with zeros
print(np.zeros((4,4))) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
#Create a 2×5 array filled with ones.
print(np.ones((2,5)))

     

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
#3. Create a 3×3 array filled with the number 7.
print(np.full((3,3),7))


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [23]:
#4. Create a 5×5 identity matrix.
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
#5. Generate numbers from 0 to 20 with step size 2 using arange().
print(np.arange(0,21,2))

[ 0  2  4  6  8 10 12 14 16 18 20]


In [26]:
#6. Generate 6 evenly spaced numbers between 10 and 50 using linspace().
print(np.linspace(10,50,6))

[10. 18. 26. 34. 42. 50.]


### Part 3: Random Functions


In [6]:
##1. Generate a 2×2 array of random numbers between 0 and 1.
import numpy as np

#print(np.random.rand(2,2))  
#print(np.random.randn(2,2))  
print(np.random.randint(0, 10, (2,2))) 

[[3 2]
 [4 6]]


In [7]:
#2. Generate a 3×3 array from normal distribution.
import numpy as np

print(np.random.rand(3,3))

[[0.55513587 0.18507496 0.01554128]
 [0.29272482 0.79510968 0.82794926]
 [0.92636757 0.84119656 0.72450581]]


In [8]:
#3. Generate a 4×4 array of random integers between 1 and 20.
import numpy as np

print(np.random.randn(4,4))

[[ 0.4753212   1.12083097  2.11946509  1.31616312]
 [-0.2608285   0.85319661 -1.2289891   1.65895221]
 [-1.34717165 -1.55847885 -1.35124221  1.57067876]
 [-0.60826975  0.67920107 -1.10750335 -1.14887481]]


In [9]:
#4. Generate a 2×5 array of random integers between 50 and 100.
import numpy as np

print(np.random.randn(2,5))

[[ 0.9702291   0.22634493  0.03164861 -0.79552036 -0.8053223 ]
 [ 0.19513579  1.24220466 -0.67606091  0.07568934 -1.72900302]]


### Part 4: Shape and Splitting

In [11]:
arr = np.array([1,2,3,4,5,6,7,8])
print(np.split(arr,2))    ##1. Split the array into two equal parts.

###2. Split the array at index positions 2 and 5.
print(np.split(arr,[2,5]))

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
[array([1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [12]:
##3. Check the shape of this array:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)



(2, 3)


In [13]:
##4. Reshape a 1D array of 12 elements into a 3×4 matrix.
arr=np.arange(1,13)
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Part 5: Matrix Operations


In [14]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))


[[19 22]
 [43 50]]


In [16]:
#2. Create a 3×3 identity matrix.
import numpy as np
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
##3. Multiply matrix A with identity matrix and observe result
A = np.array([[1,2],[3,4]])
I = np.eye(2)
print(I)
print(np.dot(A,I))

[[1. 0.]
 [0. 1.]]
[[1. 2.]
 [3. 4.]]


In [21]:
##4. Create a 3×3 matrix filled with 9 using np.full().
import numpy as np
print(np.full((3,3),9))

[[9 9 9]
 [9 9 9]
 [9 9 9]]


### Part 6: Mixed Concept Questions

In [24]:
# 1. Create an array from 1 to 100 and:
# - Find its mean
# - Find its variance
# - Find index of maximum value

arr=np.arange(1,101)
print(np.mean(arr))
print(np.var(arr))
print(np.argmax(arr))

50.5
833.25
99


In [28]:
# 2. Generate a 5×5 random integer matrix between 10 and 50 and:
# - Find maximum value
# - Find minimum value
# - Find mean of entire matrix

arr=np.arange(10,51)
a=np.random.randn(5,5)
print(a)
print("Maximum:",np.max(a))
print("MInimum:",np.min(a))
print(np.mean(a))

[[-0.61681459 -0.60637458 -1.39710772  0.28941995  0.8763389 ]
 [-1.09498953  1.57743189 -0.8454294   0.79646975  0.02448167]
 [-0.58062496  0.08885033  0.88755447  0.28755301  2.14065565]
 [-0.75782285  0.58399889  0.44481959  1.55958743  0.04596519]
 [ 0.28112853 -0.22402867 -1.06076537 -0.71353937  0.19663255]]
Maximum: 2.140655645024788
-1.3971077190932042
0.08733562968237131
